fix: fixed rclpy error rclpy._rclpy_pybind11.RCLError: failed to shutdown: rcl_shutdown already called on the given context, at ./src/rcl/init.c:241 Error occured because openset.launch launches two services that call rclpy.shutdown().