feat: unified ROS2 hri message (#416)
Further work: https://github.com/RobotecAI/rai/issues/418

refactor(partial): refactor openset tools to rai2.0 ros2ariconnector api

refactor: finalize with simplifications

fix: missing argument, missing client

workaround: don't remove subscription due to rclpy issue

https://github.com/ros2/rclpy/issues/1142

replace ros2 future waiting with more robust callback based mechanism

remove waiting from launch

fix order in connector shutdown

```
Exception in thread Thread-1 (spin):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 294, in spin
    self.spin_once()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 794, in spin_once
    self._spin_once_impl(timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 786, in _spin_once_impl
    self._executor.submit(handler)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
```

refactor: cleanup manipulation launchfile

chore: pre-commit

feat: benchmark class models

Co-authored-by: Jakub Matejczyk <jakub.matejczyk@robotec.ai>

chore: naming changes

Co-authored-by: Jakub Matejczyk <jakub.matejczyk@robotec.ai>

chore: naming changes

Co-authored-by: Jakub Matejczyk <jakub.matejczyk@robotec.ai>

chore: redefine benchmark model

Co-authored-by: Jakub Matejczyk <jakub.matejczyk@robotec.ai>
Co-authored-by: Kacper Dąbrowski <kacper.dabrowski@robotec.ai>

refactor: SceneConfig to BaseModel class

feat: add SceneSetup to store initial scene setup

build: poetry initialization of rai_benchmarks and rai_simulations

chore: add licence lines

build: create packages from rai_benchmarks and rai_simulations

chore: removed mistakenly added file

feat: scene config implementation

Add O3DEEngineConnector features

Signed-off-by: Kacper Dąbrowski <kacper.dabrowski@robotec.ai>

Remove an unused file

Signed-off-by: Kacper Dąbrowski <kacper.dabrowski@robotec.ai>

Add binary path caching

Signed-off-by: Kacper Dąbrowski <kacper.dabrowski@robotec.ai>

Add two example scenes

Signed-off-by: Kacper Dąbrowski <kacper.dabrowski@robotec.ai>

feat: replace binary path with ros2 launch command + binary path

refactor: renamed rai_sim and rai_bench

fix: fixed shutdown of binary

chore: make pose mandatory

chore: remove rai_bench because it is developed on another branch

ci: add missing license lines

laoding and spawning frm benchmark

rabsed

naming change

grab xyz benchmark

benchmarks run new sim every scenario for now

adjust to new tools

Remove psutil conflicting __del__ method from o3de connector

See this issue: https://github.com/giampaolo/psutil/issues/2437

stream langgraph agent

extent output of tool runner

enable all scenarios in the benchmark

removed name providing for manipulator launch

added move arm func to connectors

rebased and adjusted to new code

added metrics to tasks, created rai_bench package

added comments